#select the net function. defualt is the identity function
net-function-type: "mul"
#set the initial position, default is 0
initial-position: 0.1
#set the motor count. default is 0
motors-count: 10
#set the  position of each motor, default is 0
motors-initial-position: 
    0: 5.2
    2: 7.0
#set the print freqeuncy
print-each-N-cycles: 10
#set runtime limit in seconds, negative to run for ever. default is forever
run-time-limit-sec: 5.5
